### ISSUE TITLE
Error while loading audio file while trainning on colab

### ISSUE THREAD

**Issue by shoaibahmadse** [ruizhecao96/CMGAN#17]
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/CMGAN/src/data/dataloader.py", line 25, in __getitem__
    clean_ds, _ = torchaudio.load(clean_file)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/backend/sox_io_backend.py", line 152, in load
    return torch.ops.torchaudio.sox_io_load_audio_file(
RuntimeError: Error loading audio file: failed to open file /content/train/clean/.ipynb_checkpoints

**Comment by ruizhecao96** [comment]
I think the audio path is not correct, make sure they are in one dir with wav file.

**Comment by shoaibahmadse** [comment]
-dataset/
  -train/
    -noisy/
    -clean/
  -test/
    -noisy/
    -clean/

**Comment by shoaibahmadse** [comment]
![image](https://user-images.githubusercontent.com/79258797/210174061-c26f4a84-9988-4ed4-96fa-e7684af9238b.png)


and the command for training:

`!python3 /content/CMGAN/src/train.py --data_dir /content/dataset/ --batch_size 4`


**But the error remain same**

**Comment by ruizhecao96** [comment]
I think your train/clean directory has a file named .ipynb_checkpoints. you can either delete this file or filter this file in dataset.py. Add a condition with ```if '.wav' in file_path: ```
